Refactor package build
taehwanno/react-outside-click-handler pull request #7
Opened 2017-12-18 22:39 UTC by ConAntonakos

2017-12-20 01:55 UTC, taehwanno commented
Oh, Hello @ConAntonakos 😄  
I have not maintained this package because of my personal priority.
but as you said, this package must be updated.
I will look into it on weekend. Thanks for your contribution.

2017-12-27 16:47 UTC, taehwanno requested changes
Sorry for late response. lately, I am having a little busy day 😢  Thanks.

2017-12-27 16:47 UTC, taehwanno commented on rollup.config.js
> +};
In current rollup configuration, react also bundled to the output file. we need to add `external` and `globals` options for React.

- https://rollupjs.org/#peer-dependencies
- https://rollupjs.org/#external-e-external-
- https://rollupjs.org/#globals-g-globals-
- https://github.com/taehwanno/react-github-renderer/blob/ef4ae43ffd3658515b337de01aa61d7043534e2a/rollup.config.js#L31-L34

2017-12-27 16:47 UTC, taehwanno commented on rollup.config.js
> +  plugins = [...plugins, uglify({}, minify)];
In `dist` output directory, bundling format must be `umd` because of a user that not use bundle system. `es` need bundle system like webpack to use in production.

2017-12-27 16:47 UTC, taehwanno commented on rollup.config.js
> +const MODULE_NAME = 'react-outside-click-handler';
Please change `MODULE_NAME` to `ReactOutsideClickHandler` for consistency and compatibility.

https://github.com/taehwanno/react-outside-click-handler/blob/9943b02cbe2f79eff0b0f0b5a8152d7485b6aa98/webpack.dist.config.js#L19

2017-12-27 16:47 UTC, taehwanno commented on package.json
> +  },
Please re-add eslint with airbnb preset

- https://github.com/airbnb/react-dates/blob/master/package.json#L77-L82
- https://github.com/airbnb/react-dates/blob/master/.eslintrc
- https://github.com/airbnb/react-dates/blob/master/.eslintignore

2017-12-27 16:47 UTC, taehwanno commented on test/OutsideClickHandler.spec.jsx
> +  describe.skip('lifecycle methods', () => {
In order to use jest, we need some works. 

jest has `describe.skip`. so below four unit tests are skipped. Additionally, we have to use [jest-wrap](https://github.com/airbnb/jest-wrap#skiponly) instead of [mocha-wrap](https://github.com/airbnb/mocha-wrap). but as you can see in [this](https://github.com/airbnb/jest-wrap#skiponly), it's not possible to implement `describe.skip` in jest-wrap so that we won't have same test codes with airbnb/react-dates. 

As a result, we have to test with only jest API without chai, sinon-sandbox, jest-wrap. because this package isn't a mirror of airbnb/react-dates's `OutsideClickHandler`, I think it's fine.

2017-12-27 18:07 UTC, ConAntonakos commented on package.json
> +  },
I removed eslint since I decided to integrate [prettier] to not have to think about file formatting ((https://prettier.io/) (https://github.com/ConAntonakos/react-outside-click-handler/blob/refactor-package-build/package.json#L84). What do you think about it?

2017-12-27 18:08 UTC, ConAntonakos commented on rollup.config.js
> +  plugins = [...plugins, uglify({}, minify)];
Got it! It's my first time actually building a working Rollup configuration. So, use `umd` for both prod and dev builds?

2017-12-27 19:29 UTC, ConAntonakos commented on test/OutsideClickHandler.spec.jsx
> +  describe.skip('lifecycle methods', () => {
I basically brought over whatever airbnb/react-dates test suite had for this component. I guess we don't have to have the same tests; plus, I'll share this repo with the airbnb/react-dates team after we're happy with it. I can cut out chai, mocha-wrap, and sinon since some of their capabilities are already within jest.

2018-01-01 05:11 UTC, taehwanno commented on package.json
> +  },
Please see [ljharb's comment in airbnb styleguide](https://github.com/airbnb/javascript/issues/1548#issuecomment-326878869).
I agree with his think. formatter (prettier) is not a replacement for linter (eslint). So, a linter is always required to the developer. 

I think that we can choice eslint alone or eslint with prettier. but I wanna make this choice in another pull request.

2018-01-01 05:17 UTC, taehwanno commented on rollup.config.js
> +  plugins = [...plugins, uglify({}, minify)];
> Got it! It's my first time actually building a working Rollup configuration. So, use umd for both prod and dev builds?

Yes. 😄  

Generally, npm package has been published with files like commonjs, es module, umd, umd with uglification. but I have published only umd.

2018-01-01 05:19 UTC, taehwanno commented on test/OutsideClickHandler.spec.jsx
> +  describe.skip('lifecycle methods', () => {
Yeah. it's a right direction 👍

2018-04-01 14:36 UTC, taehwanno commented
@ConAntonakos I divided this pull request to small ones. 
If you want to look for related works, you can see in [releases page](https://github.com/taehwanno/react-outside-click-handler/releases). 

Appreciate your contribution :pray: Thanks.

2018-04-01 14:36 UTC, closed without merging

2018-04-02 01:32 UTC, ConAntonakos commented
@taehwanno Hey! I'm really sorry I didn't have a chance to finish this pull request. These past few months have been busy. Please let me know what your progress is, and where I can jump in! Thanks!

2018-06-05 22:28 UTC, ConAntonakos commented
It looks like Airbnb published their own version! https://github.com/airbnb/react-outside-click-handler

2018-06-06 14:22 UTC, taehwanno commented
@ConAntonakos 

Yepp. I added Airbnb as a maintainer of the `react-outside-click-handler`.
I will clarify maintenance issue about this package to README.md.
Thanks for letting me know :)